### ISSUE TITLE
Invalid command "project_diff_preview"  

### ISSUE THREAD

**Issue by ray-x** [tanvirtin/vgit.nvim#106]
### Description
enter :
:VGit project_diff_preview
Got above errors

Is this command out of date?

Also a few commands not working (no output)
e.g.  VGit buffer_history

My config:
```
require('vgit').setup()
```
Is there any field that needs to setup to non-default to allow those commands to be working?

- nvim --version output: nvim-0.6.0
- Operating system:  Mac

**Comment by tanvirtin** [comment]
Hi! Sorry for the inconvenience, I pushed some recent commits renaming some commands and made a typo on the command `project_diff_preview`, it should be fixed now.

Regarding the command `buffer_history`, it only works when you have a buffer related to a git file. So you have to execute the command while being on the buffer. If that doesn't work let me know!

**Comment by ray-x** [comment]
I think there might be something wired when I lazy load the plugin. If is lazyloaded, some of the commands may not work. I will enable the logs and see what is going on.

**Comment by ray-x** [comment]
Ok, seems related to lazyloading.  It works well now with lazy disabled.
