### ISSUE TITLE
Support lazyload

### ISSUE THREAD

**Issue by ray-x** [tanvirtin/vgit.nvim#109]
**Issue** 

When setup VGIt, the VGit buffer attach is hook to  ` events.on('BufWinEnter', ':lua require("vgit")._buf_attach()')`

This can be a problem if I would like to load the plugin on first `VGit` command, or, maybe on event `BufWinEnter/CmdlineEnter`.

**Describe the solutions you'd like**
* In setup, attach the current buffer
* BufferCache, if cache missed, try to load the buffer and return nil only when the buffer add is failed.

**Comment by tanvirtin** [comment]
Hey, thanks for the issue. I appreciate your efforts in helping me make `VGit` a better plugin!

If there are any issues related to this feel free to let me know.
