### ISSUE TITLE
undo hunk stage

### ISSUE THREAD

**Issue by ray-x** [tanvirtin/vgit.nvim#114]
**Describe the solution you'd like**
Add option to unstage a hunk
buffer_hunk_unstage

**Comment by nyngwang** [comment]
I need this too

**Comment by tanvirtin** [comment]
Any UI ideas on how you want this implemented?

**Comment by ray-x** [comment]
Simply function/keymap would do. So we can toggle Stage/Unstage

**Comment by tanvirtin** [comment]
How would you know you are currently on a staged hunk? There is no visual indicator on the main buffer to determine it. The gutter signs only show diff against index.

One idea I had was to add this functionality inside `buffer_diff_staged_preview` which shows all the hunks that you staged. Thoughts?

**Comment by ray-x** [comment]
I am ok with a new function of buffer_diff_staged_preview (quickfix).   But it would be more natural to jump between the hunks (staged and non-staged) and toggle the stage. 
In lots of cases, it is a one time thing. I incidentally staged something and would like to undo the stage.

**Comment by nyngwang** [comment]
@tanvirtin: Sorry for being rude. But I have been waiting for 3 months about the fix of this.
