### ISSUE TITLE
Separate highlight for hunk_preview

### ISSUE THREAD

**Issue by fedoranvar** [tanvirtin/vgit.nvim#128]
Good day to you!

Is it possible to define different from `Normal` background color  for `buffer_hunk_preview` ?

: to be able to make `VGitNormal` darker
![image](https://user-images.githubusercontent.com/52028706/133999028-2038fe0a-1387-40ed-a46a-42e665b4469b.png)

Thank you!

**Comment by tanvirtin** [comment]
@fedoranvar It's absolutely possible! I don't have a `VGitNormal` hl but you can pass in any highlight of your choice [here](https://github.com/tanvirtin/vgit.nvim/blob/main/lua/vgit/layouts/default.lua#L12).

I tried to create a way users can modify how `VGit` layout is structured. Feel free to modify this [file](https://github.com/tanvirtin/vgit.nvim/blob/main/lua/vgit/layouts/default.lua) as much as you want. This layout file then gets read from various previews for example [here](https://github.com/tanvirtin/vgit.nvim/blob/main/lua/vgit/previews/HistoryPreview.lua#L7). You can also create your own layout and source it via advanced setup (You can also add your layout as PR so others can use it as well!).

Hunk preview has some restriction regarding custom positioning. Ill have to tackle that in the future, as right now you it only appears near your cursor.

If you find any bugs/issues related to this feature let me know, and feel free to close this issue as you please.

**Comment by fedoranvar** [comment]
@tanvirtin 

Got it!
Here is how i've managed to do it:

```lua
local my_layout = vgit.layouts.default

my_layout.hunk_preview.background_hl = 'NormalFloat'
...
    render = {
        layout = my_layout,
```

![image](https://user-images.githubusercontent.com/52028706/134162365-c2aafb7c-c979-4dad-9cf2-591dc493f05b.png)


Thank you!

**Comment by tristone13th** [comment]
> 

thank, but why the diff area doesn't have highlights?
