### ISSUE TITLE
Support yadm

### ISSUE THREAD

**Issue by ouuan** [tanvirtin/vgit.nvim#149]
[yadm](https://github.com/TheLocehiliosan/yadm) is a Git-based dotfiles manager. Basically, it manages a Git repo whose work tree is the `$HOME` directory. `yadm` can be used to run any git commands, such as `yadm status`, `yadm add`, `yadm diff`. It would be great to support it.

https://github.com/lewis6991/gitsigns.nvim supports yadm. Maybe https://github.com/lewis6991/gitsigns.nvim/blob/a6d1574babd96b53102677e50c65f916d388708e/lua/gitsigns/git.lua#L261 could be helpful.

**Comment by bennypowers** [comment]
this tutorial accomplishes a similar goal without requiring a package install:

https://www.atlassian.com/git/tutorials/dotfiles

Essentially, it would be nice to be able to configure vgit such that files in `~/.config/**/*` would have their git dir in `~/.cfg` instead of `~/.git`

**Comment by ibhagwan** [comment]
@ouuan @bennypowers, try out #218, works great so far.
