### ISSUE TITLE
VGit Ex commands make it stop working.

### ISSUE THREAD

**Issue by vspecky** [tanvirtin/vgit.nvim#151]
### Description

VGit stops working when an ex command (VGit specific) is executed.

When the keybindings are defined in the config like below, VGit works flawlessly. The issue arises when you try to execute VGit with a ex command, like `:VGit buffer_hunk_preview` for example, which makes VGit stop working altogether. At this point, resourcing the config file solves the issue as found out by someone in #121 , but the issue arises again if you use an ex command.

```
lua << EOF
local vgit = require('vgit');
local utils = require('vgit.utils');

vgit.setup {
    debug = true,
    keymaps = {
        ['n <C-k>'] = 'hunk_up',
        ['n <C-j>'] = 'hunk_down',
        ['n <leader>gs'] = 'buffer_hunk_stage',
        ['n <leader>gr'] = 'buffer_hunk_reset',
        ['n <leader>gp'] = 'buffer_hunk_preview',
        ['n <leader>gb'] = 'buffer_blame_preview',
        ['n <leader>gf'] = 'buffer_diff_preview',
        ['n <leader>gh'] = 'buffer_history_preview',
        ['n <leader>gu'] = 'buffer_reset',
        ['n <leader>gg'] = 'buffer_gutter_blame_preview',
        ['n <leader>gd'] = 'show_debug_logs',
        ['n <leader>gq'] = 'project',
        ['n <leader>gx'] = 'toggle_diff_preference',
    }
}
EOF
```
### Debug Logs
Can't show any since the command won't work.

### Version info
- nvim --version output: NVIM v0.5.1
- Operating system: Pop!_OS 20.04 LTS

**Comment by danielnehrig** [comment]
i am having the same issue really unfortunate

**Comment by tanvirtin** [comment]
Hey there, please upgrade your `Neovim` and `VGit` to the latest version. This should hopefully be fixed, if not feel free to reopen this issue thank you!
