### ISSUE TITLE
Add API to get diff for statusline

### ISSUE THREAD

**Issue by Shatur** [tanvirtin/vgit.nvim#157]
**Describe the solution you'd like**

In the statusline, users often display numbers with the number of additions / changes / deletions. Since already vgit processes this information to place signs, it would be convenient to be able to get it using lua.
For example, with [gitsigns](https://github.com/lewis6991/gitsigns.nvim) plugin I can get this information using `vim.b.gitsigns_status_dict`.

**Comment by ibhagwan** [comment]
@Shatur, take a look at #218, if you wish to try it out [use my fork](https://github.com/ibhagwan/vgit.nvim) for now.
