### ISSUE TITLE
Error executing luv callback

### ISSUE THREAD

**Issue by Shatur** [tanvirtin/vgit.nvim#160]
### Description

If I open the buffer, make changes and save it, then I get the following errors:

```
"plugin/telescope.lua" 89L, 3668C записано
Error executing luv callback:
...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
stack traceback:
	[C]: in function 'error'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
Error executing luv callback:
...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
stack traceback:
	[C]: in function 'error'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
Error executing luv callback:
...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
stack traceback:
	[C]: in function 'error'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
Error executing luv callback:
...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
stack traceback:
	[C]: in function 'error'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
Error executing luv callback:
...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
stack traceback:
	[C]: in function 'error'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
Error executing luv callback:
...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
stack traceback:
	[C]: in function 'error'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
```

I think you should wrap the callback into `vim.schedule` or `vim.schedule_wrap`.

- nvim --version output: 
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: ArchLinux

**Comment by imSafdarAwan** [comment]
> ### Description
> If I open the buffer, make changes and save it, then I get the following errors:
> 
> ```
> "plugin/telescope.lua" 89L, 3668C записано
> Error executing luv callback:
> ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
> stack traceback:
> 	[C]: in function 'error'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
> Error executing luv callback:
> ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
> stack traceback:
> 	[C]: in function 'error'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
> Error executing luv callback:
> ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
> stack traceback:
> 	[C]: in function 'error'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
> Error executing luv callback:
> ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
> stack traceback:
> 	[C]: in function 'error'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
> Error executing luv callback:
> ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
> stack traceback:
> 	[C]: in function 'error'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
> Error executing luv callback:
> ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...im/pack/plugins/start/vgit.nvim/lua/vgit/core/Buffer.lua:79: E5560: nvim_buf_is_valid must not be called in a lua loop callback
> stack traceback:
> 	[C]: in function 'error'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
> 	...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:112>
> ```
> 
> I think you should wrap the callback into `vim.schedule` or `vim.schedule_wrap`.
> 
> * nvim --version output:
> 
> ```
> NVIM v0.6.0
> Build type: Release
> LuaJIT 2.0.5
> Compiled by builduser
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
> ```
> 
> * Operating system: ArchLinux

same error
![image](https://user-images.githubusercontent.com/87114084/147599612-f6cfca8d-29ae-4ffb-a0af-795ff4800a42.png)

**Comment by tanvirtin** [comment]
Happening due to some inconsistent race conditions. Bug can vary between systems. I issued a fix but if you see these errors again please feel free to open this back up.

Appreciate all error reports 👍🏾
