### ISSUE TITLE
project_diff_preview project_hunks_preview error

### ISSUE THREAD

**Issue by ray-x** [tanvirtin/vgit.nvim#177]
### Description

A clear and concise description of your bug.
Error:  'icon' (a nil value) 

- nvim --version output: nvim-6.1 release
- Operating system: Mac

Error executing vim.schedule lua callback: ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...te/pac
k/packer/opt/vgit.nvim/lua/vgit/ui/table_maker.lua:15: attempt to get length of field 'icon' (a nil value)                                                  
stack traceback:                                                                                                                                            
        [C]: in function 'error'                                                                                                                            
        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'       

vgit setup
```lua
function config.vgit()
  -- use this as a diff tool (faster than Diffview)
  -- there are overlaps with gitgutter. following are nice features
  require('vgit').setup({
    keymaps = {
      ['n <leader>ga'] = 'actions', -- show all commands in telescope
      ['n <leader>ba'] = 'buffer_gutter_blame_preview', -- show all blames
      ['n <leader>bp'] = 'buffer_blame_preview', -- buffer diff
      ['n <leader>bh'] = 'buffer_history_preview', -- buffer commit history DiffviewFileHistory
      ['n <leader>gp'] = 'buffer_staged_diff_preview', -- diff for staged changes
      ['n <leader>pd'] = 'project_diff_preview' -- diffview is slow
    },
    controller = {
      hunks_enabled = false, -- gitsigns
      blames_enabled = false,
      diff_strategy = 'index',
      diff_preference = 'vertical',
      predict_hunk_signs = true,
      predict_hunk_throttle_ms = 500,
      predict_hunk_max_lines = 50000,
      blame_line_throttle_ms = 250,
      show_untracked_file_signs = true,
      action_delay_ms = 500
    }
  })
  require"packer".loader("telescope.nvim")
  -- print('vgit')
  -- require("vgit")._buf_attach()
end

```

**Comment by tanvirtin** [comment]
This issue is occuring due to icons in the table not being found.

I will issue a fix soon. Thanks for reporting!
