### ISSUE TITLE
Allow passing branch/ref to diff command

### ISSUE THREAD

**Issue by rawhat** [tanvirtin/vgit.nvim#188]
**Describe the solution you'd like**

One thing in my other git plugin(s) workflow is to diff against a specific branch.  For example:  `:Gdiff origin/staging` or `:Gdiff HEAD~3`.  It would be useful to diff against things other than just the current HEAD.  I couldn't determine if this functionality already exists, so if it does, my apologies!

This plugin is really cool, thank you :)

**Comment by tanvirtin** [comment]
Hey, thanks for the feature request. This feature does not exist currently and it would bring great value.

I think both `buffer_diff_preview` and `project_diff_preview` could benefit from this feature.

For `buffer_diff_preview` we would need to pass an additional option [here](https://github.com/tanvirtin/vgit.nvim/blob/main/lua/vgit/features/scenes/DiffScene.lua#L98) and fetch the appropriate data [here](https://github.com/tanvirtin/vgit.nvim/blob/main/lua/vgit/features/scenes/DiffScene.lua#L24) and I that should be it.
