### ISSUE TITLE
support for setting the base to something other than HEAD

### ISSUE THREAD

**Issue by lukas-reineke** [tanvirtin/vgit.nvim#19]
It would be nice to be able to change the base on the fly to another commit.
This allows for example to keep committing on a feature branch, but compare the current state against the develop branch.
Or, check out a Pull Request and compare it to the target branch.

Other plugins implement this, eg.
https://github.com/airblade/vim-gitgutter#the-base-of-the-diff

**Comment by tanvirtin** [comment]
Thanks for the suggestion, this would be a good addition, I'll be working on it.
