### ISSUE TITLE
Wrong background color in diff mode

### ISSUE THREAD

**Issue by hexh250786313** [tanvirtin/vgit.nvim#190]
### Description

- nvim --version output: 
   ```
    NVIM v0.7.0-dev+733-gb1757e1c2
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/hexh/desktop/neovim/build/config -I/home/hexh/desktop/neovim/src -I/home/hexh/desktop/neovim/.deps/usr/include -I/usr/include -I/home/hexh/desktop/neovim/build/src/nvim/auto -I/home/hexh/desktop/neovim/build/include
    Compiled by hexh@hexh

    Features: +acl +iconv +tui
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/share/nvim"

    Run :checkhealth for more info

   ```
- Operating system: 
  - Manjaro Linux x86_64 5.10.89-1-MANJARO
 
#### Record

https://user-images.githubusercontent.com/26080416/148767236-cac200cb-e46f-4ce1-aa93-3ef6e0abef51.mp4

- Steps(Look at the video)
  1. call `:VGit buffer_history_preview`
  2. Locate to `HEAD~2` and there is one line change(line 98)
  3. Locate to `HEAD~3` and there are many changes. The line 66 to line 88 displays green background but it has no change commit actually.
  4. Go back to `HEAD~2`. You can see the right panel is different than step 2. It shows more green lines abnormally.

- config
   ```
   require("vgit").setup({})
   ```

In fact I do not konw how to reproduce this issue accurately so I record this video.

**Comment by tanvirtin** [comment]
Hey, thanks for the issue. It's hard for me to find bugs like these because of all the possibilities, so I really appreciate it.

It looks like an issue with stale painting that is not being cleared as you switch files, I will try to reproduce and issue a fix.

**Comment by tanvirtin** [comment]
@hexh250786313 Just pushed an update, let me know if you are still facing this issue.

**Comment by hexh250786313** [comment]
@tanvirtin I pull the update, but it does not work. Then I try disable my plugins one by one. Finally I found [focus.nvim](https://github.com/beauwilliams/focus.nvim) caused the issue. `focus.nvim` helps auto-resize the focused window. Actually it was not a required function for me. Now I disable `focus.nvim` and everything works fine. But I hope there is a better way to fix it.

**Comment by hexh250786313** [comment]
I tried several ways to combine Focus.nvim with vgit.nvim, but I found Focus.nvim had many rendering issues except current issue. I gave up Focus.nvim.

Issue close!
