### ISSUE TITLE
Conflicts  | Allow users to manage conflicts

### ISSUE THREAD

**Issue by tanvirtin** [tanvirtin/vgit.nvim#196]

**Comment by bennypowers** [comment]
I encourage you to take a look at Atom's Github plugin's UI for this, which is excellent.

In addition, even after years of using similar tools, I'm consistently confused by terminology like "resolve as ours" vs "resolve as theirs". Would it make sense to label conflict blocks based on their associated commit messages, perhaps with an optional floating window that would provide more information?
