### ISSUE TITLE
Git blame for several lines or whole buffer

### ISSUE THREAD

**Issue by timsofteng** [tanvirtin/vgit.nvim#20]
Hello. Can I somehow toggle git blame for whole file or block of lines?

**Comment by tanvirtin** [comment]
Right now you can enable and disable blames for all buffers, but option to enable and disable them for individual buffers has not been implemented yet. It should not be that hard to implement and I should be able to add it soon.

**Comment by timsofteng** [comment]
> Right now you can enable and disable blames for all buffers, but option to enable and disable them for individual buffers has not been implemented yet. It should not be that hard to implement and I should be able to add it soon.

Got it. How can I do it? Right now I only can toggle blame for current line.

**Comment by tanvirtin** [comment]
> > Right now you can enable and disable blames for all buffers, but option to enable and disable them for individual buffers has not been implemented yet. It should not be that hard to implement and I should be able to add it soon.
> 
> Got it. How can I do it? Right now I only can toggle blame for current line.

This feature does not exist currently. It needs to be implemented.
