### ISSUE TITLE
Jump back to the wrong window when closing the result window of `VGit buffer_hunk_preview`.

### ISSUE THREAD

**Issue by nyngwang** [tanvirtin/vgit.nvim#209]
### Description

Jump back to the wrong window when closing the result window of `VGit buffer_hunk_preview`. And what's ridiculous is that I have tried `wincmd p` but it doesn't work :(

## nvim --version output: 
```
NVIM v0.7.0-dev+1041-g07c97fa02
Build type: Release
LuaJIT 2.1.0-beta3
```

## Operating system: 
macOS 11.6.2

**Comment by tanvirtin** [comment]
Hey not sure I fully understand the problem. Is this when you have multiple split windows open and then you quit the buffer hunk preview window? Closing any VGit window should get rid of all the related windows its currently showing.

Would love to solve this issue and some more details would help, thanks!

**Comment by nyngwang** [comment]
The cursor will be located at the left window, as shown in the step 3., but what I meant is that since I call the `VGit buffer_hunk_preview` in the first step, so the position is wrong. The cursor should be located in the window where the command is called. Clear?

<img src="https://user-images.githubusercontent.com/24765272/153541805-32f9a3ae-33e1-47a1-9e18-048997639e1d.png" width="600">
