### ISSUE TITLE
functions to get info about the current git state

### ISSUE THREAD

**Issue by classabbyamp** [tanvirtin/vgit.nvim#212]
I'm moving from fugitive + gitgutter and use `FugitiveHead()` to get the current branch and `GitGutterGetHunkSummary()` to get the number of added, modified, and removed lines for my statusline, like so:

```vim
function! LightlineGitStatus()
    if exists('*FugitiveHead')
        let branch = FugitiveHead()
        if branch !=? ''
            let [a,m,r] = GitGutterGetHunkSummary()
            return printf('<%s> +%d ~%d -%d', branch, a, m, r)
        endif
    endif
    return ''
endfunction
```

it would be nice to be able to have this behaviour in vgit

**Comment by classabbyamp** [comment]
whoops looks like #157 covers half of this

**Comment by ibhagwan** [comment]
@classabbyamp, take a look at #218, if you wish to try it out [use my fork](https://github.com/ibhagwan/vgit.nvim) for now.
