### ISSUE TITLE
How to wait for an async call to finish?

### ISSUE THREAD

**Issue by nyngwang** [tanvirtin/vgit.nvim#213]
As title. I'm trying to run commands only after the `buffer_hunk_stage()` call is completed. I want to restore the view of the current window.

**Comment by tanvirtin** [comment]
Oh interesting requirement, don't think there's a straight forward way as of now to know for sure. I'll probably add an additional parameter to pass callbacks on certain VGit commands.

**Comment by nyngwang** [comment]
@tanvirtin:

If this can be easily done, please do so. The following is a workaround I'm currently using because of the lack of this functionality:

```lua
vim.keymap.set('n', '<Leader>ga', function ()
  local view = vim.fn.winsaveview()
  vim.cmd('VGit buffer_hunk_stage')
  vim.cmd('sleep 50m')
  vim.fn.winrestview(view)
end, NOREF_NOERR_TRUNC)
```

**Comment by tanvirtin** [comment]
Nice, thanks for the feedback and clarification on why you needed to do this. The centering is happening because of the `edit` command that gets executed. I am more inclined to make the current view not center after such actions rather than passing callback.

**Comment by nyngwang** [comment]
@tanvirtin That's great. Thanks for your acknowledgment. Wait for the update!

**Comment by nyngwang** [comment]
I just removed the hot-fix from my previous comment. Now it's simple and intuitive. Thank you!
