### ISSUE TITLE
LiveGutter disappeared after running `:edit`

### ISSUE THREAD

**Issue by nyngwang** [tanvirtin/vgit.nvim#217]
### Description

As title.

- nvim --version output: 
  ```
  NVIM v0.8.0-dev+60-ga75efc237
  Build type: Release
  LuaJIT 2.1.0-beta3
  ```

- Operating system: macOS 12.3.1

**Comment by tanvirtin** [comment]
Failing to reproduce this on my end, would love to have more info in trying to close this one out. Is this still happening on your end after the latest commits?

**Comment by nyngwang** [comment]
@tanvirtin: This has been fixed! I just checked it.

**Comment by tanvirtin** [comment]
Thanks for confirming!
