### ISSUE TITLE
Multiple signature at the end of the file after calling `buffer_hunk_stage` many times.

### ISSUE THREAD

**Issue by nyngwang** [tanvirtin/vgit.nvim#221]
### Description

As title.

- nvim --version output: 
    ```
    NVIM v0.8.0-dev+112-g13520aae1
    Build type: Release
    LuaJIT 2.1.0-beta3
    ```
- Operating system: macOS 12.3.1

<img src="https://user-images.githubusercontent.com/24765272/166404051-0204d8fa-761b-4271-a885-d1be150a7cc8.png" width="400">

**Comment by tanvirtin** [comment]
The Authorship Code Lens feature needs a bit more love from my end, I had previously turned this feature off by default, for a temporary fix please turn it off for the time being, I should get to it soon!

```
   authorship_code_lens = {
      enabled = false,
    },
```

**Comment by nyngwang** [comment]
Thanks!
