### ISSUE TITLE
Make 'hunk_up', 'hunk_down' work inside diff preview screens

### ISSUE THREAD

**Issue by ibhagwan** [tanvirtin/vgit.nvim#224]
I have `]c` and `]c` mapped to hunk up/down respectively, would be nice to be able to navigate between the hunks in the different diff views: `buffer_hunk_preview`, `buffer_diff_preview` and `project_diff_preview` (similar to `gitsigns`).

**Comment by tanvirtin** [comment]
This is something that's in place. Any diff in `VGit` (buffer_hunk_preview, project_diff_preview, project_hunks_preview, buffer_history_preview, etc) should be navigatable by the `:VGit hunk_up` and `:VGit hunk_down`. In fact you can even execute these commands while you are now focused on the window itself and move around the diffs.

If this isn't working, let me know it should be classified as a bug.

**Comment by ibhagwan** [comment]
> If this isn't working, let me know it should be classified as a bug.

I tried `:VGit next_hunk` and all diff popup screens, I guess it’s a bug, what would be the best way to debug this? If you wish I can dive into the code and see what I can find out :)

**Comment by tanvirtin** [comment]
> > If this isn't working, let me know it should be classified as a bug.
> 
> I tried `:VGit next_hunk` and all diff popup screens, I guess it’s a bug, what would be the best way to debug this? If you wish I can dive into the code and see what I can find out :)

VGit doesn't have `next_hunk` as a command only `hunk_up` and `hunk_down`.

**Comment by ibhagwan** [comment]
> VGit doesn't have `next_hunk` as a command only `hunk_up` and `hunk_down`.

My bad, I’m not at the computer and mistyped the command names, I tried the commands that had auto complete as well aa the defined binds, I’ll do some digging and keep you posted.

**Comment by tanvirtin** [comment]
Okay this is my bad. It was something that existed [before](https://github.com/tanvirtin/vgit.nvim/blob/9a2ef0b0edede4dcf35cc53801eed4c7cdd15605/lua/vgit.lua#L134), but got changed with commit `e5ba3240258a5097eb149369136e2663dd3d5e71`.

I'll classify this as a bug, I hardcoded the navigation keys for all `previews` with `<C-j>`, <C-k>` -- [ProjectDiffScreen](https://github.com/tanvirtin/vgit.nvim/blob/main/lua/vgit/features/screens/ProjectDiffScreen/init.lua#L290). 😅

**Comment by ibhagwan** [comment]
>I'll classify this as a bug, I hardcoded the navigation keys for all previews with <C-j>

Yap `<C-J>` works :-)

Though something strange is happening, the hardcoded `<C-j>` works but running `:VGit hunk_down` or `:lua require("vgit").hunk_up()` doesn't work.

**Comment by tanvirtin** [comment]
> Though something strange is happening, the hardcoded `<C-j>` works but running `:VGit hunk_down` or `:lua require("vgit").hunk_up()` doesn't work.

Yup that's a bug, and the hardcoded `<C-j>` is not something desirable either. `hunk_up` and `hunk_down` is no longer controlling the screen.

**Comment by tanvirtin** [comment]
Thanks for bringing this issue up! Should be fixed now.
