### ISSUE TITLE
gutter causes cursor to jump around

### ISSUE THREAD

**Issue by classabbyamp** [tanvirtin/vgit.nvim#236]
### Description

With live gutter enabled, the left edge of the screen bounces around as I type (example: https://asciinema.org/a/492847)

- nvim --version output:
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by void-buildslave@a-fsn-de

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: void linux

**Comment by ryan-talus** [comment]
That looks more jittery than it should, for sure, but it looks like you don't have `vim.wo.signcolumn = 'yes'` or `set signcolumn=yes` set; if you don't have that set there will always be some jumping as you make the first change.

**Comment by Danielwsx64** [comment]
I had the same issue but setting `signcolumn=yes` fixed it.
