### ISSUE TITLE
[Question] How to stage hunk

### ISSUE THREAD

**Issue by lukepighetti** [tanvirtin/vgit.nvim#281]
After using `:VGit project_diff_preview`, I want to stage individual hunks. I see the helper to `stage hunk: gs` but I don't see a way to move the cursor to the right pane to interact with the code lines. Any insights?

<img width="1512" alt="Screen Shot 2022-09-08 at 9 29 23 AM" src="https://user-images.githubusercontent.com/666539/189134832-3d5e217c-297c-46f6-8441-f7afedcab7e2.png">

**Comment by tanvirtin** [comment]
> After using `:VGit project_diff_preview`, I want to stage individual hunks. I see the helper to `stage hunk: gs` but I don't see a way to move the cursor to the right pane to interact with the code lines. Any insights?
> 
> <img alt="Screen Shot 2022-09-08 at 9 29 23 AM" width="1512" src="https://user-images.githubusercontent.com/666539/189134832-3d5e217c-297c-46f6-8441-f7afedcab7e2.png">

To move cursor to the right pane you can do `winc w` or if you have mouse enabled you can click on the window to focus on it.

After the window is focused moving your cursor on the hunk you want to stage and using `gs` you should be able to stage the hunk.
