### ISSUE TITLE
How do I open a file from the project diff preview?

### ISSUE THREAD

**Issue by vE5li** [tanvirtin/vgit.nvim#299]
The docs state that opening files is supported but I can't find the binding anywhere, neither in the documentation nor in the code.

**Comment by aasutossh** [comment]
Press `Enter` key?

**Comment by vE5li** [comment]
Well it's not working for me.

**Comment by nickcercone** [comment]
Same problem, I can only see the tree when calling VGit project_diff_preview and cannot open/preview any of the files/changes.

**Comment by tanvirtin** [comment]
Pressing enter on any preview window should work. Can you provide me with a minimal Neovim config to reproduce this issue with `VGit` version `v0.2.0`?

**Comment by vE5li** [comment]
I was able to figure out what caused this problem. I had some autocommands setup that looked like this:
```lua
vim.api.nvim_command([[
    autocmd WinEnter * set cul
    autocmd WinLeave * set nocul
]])
```
Putting this in an `augroup` already fixed it for me.

**Comment by JulianH99** [comment]
I'm having the same issue, and not only on project diff but also when previewing commits for a file
