### ISSUE TITLE
Ability to scroll and navigate inside buffer_history_preview()

### ISSUE THREAD

**Issue by mrded** [tanvirtin/vgit.nvim#302]
It's probably me being stupid, but I don't understand how to scroll a file history preview.

When I open `:lua require('vgit').buffer_history_preview()` it only shows the top of the change, and there is no way to see or navigate in the buffer with changes.

**Comment by tanvirtin** [comment]
Hey the example (requires you to be on the `v0.2.0`) below shows you how to set the keys `C-k` and `C-j` to enable hunk navigation on any VGit previews.

```lua
require('vgit').setup({
  keymaps = {
    ['n <C-k>'] = 'hunk_up',
    ['n <C-j>'] = 'hunk_down',
  },
})
```

This should hopefully allow you to navigate through the diffs easily. The exact commands can also be used on regular buffers that contain hunk signs.
