### ISSUE TITLE
certain buffers do not react to selection moving up and down

### ISSUE THREAD

**Issue by vE5li** [tanvirtin/vgit.nvim#326]
The `project_diff_preview`, `buffer_history_preview`, and `project_hunks_preview` only change the selection when using `j` and `k`. When moving the with the arrow keys for example, only the visual selection changes. When you move the selection with the arrow keys and then press `j` or `k` the correct item will be selected.

This worked fine until two days ago so I believe that this is a regression from the recent changes.

- nvim --version output: NVIM v0.8.2
- Operating system: Arch Linux

**Comment by tanvirtin** [comment]
Closed by: https://github.com/tanvirtin/vgit.nvim/pull/357
