### ISSUE TITLE
Phantom inline git-blame messages at the bottom of buffers

### ISSUE THREAD

**Issue by mrded** [tanvirtin/vgit.nvim#333]
### Description

I've just updated from v0.1.2 to v0.2.1 with a very minimal config, and noticed phantom inline git-blame messages at the bottom of buffers.

I believe I have it all disabled. This looks like a bug to me, please advise. 
```
    require('vgit').setup({
      settings = {
        live_blame = { enabled = false },
        live_gutter = { enabled = false },
      }
    })
```

Opening a directory with nvimtree buffer:
![image](https://user-images.githubusercontent.com/347098/222005636-9bccdd16-01fc-4411-924c-9ddc5e7c1905.png)

Opening a file:
![image](https://user-images.githubusercontent.com/347098/222005771-0af3779e-f52f-44ce-a795-4b37bee77fa7.png)

I only see the message when a buffer is in focus.

- nvim --version output: NVIM v0.8.3
- Operating system: macOs 13.2.1 (22D68)
- vgit version: v0.2.1

**Comment by tanvirtin** [comment]
Hey, this is actually a feature lol. It is showing you the author that committed the most lines in this file, more like a code owner of that file. You can disable it using the following:

```lua
require('vgit').setup({
    settings = {
        authorship_code_lens = { enabled = false },
    }
})
```

**Comment by mrded** [comment]
Thanks for the reply. I don't think it should be enabled by default, as it's very confusing.

Also it triggers on random buffers, not only on files.
