### ISSUE TITLE
[Question] How do I switch views between filed on `VGit project_diff_preview`?

### ISSUE THREAD

**Issue by luislvasquez** [tanvirtin/vgit.nvim#339]
Not sure if am missing some detail from the docs, but how do I select the next/prev file while on `project_diff_preview` view?

**Comment by JulianH99** [comment]
Enter key does not work for me, I do not have auto commands or anything in between

**Comment by luislvasquez** [comment]
Any updates on this?

**Comment by Ternvein** [comment]
It's `j` and `k`. Related to #344.
