### ISSUE TITLE
Press q to record macro not working

### ISSUE THREAD

**Issue by bumaociyuan** [tanvirtin/vgit.nvim#342]
### Description

Press q to record macro not working

- nvim --version output: v0.8.3
- Operating system: macOS 12.6

**Comment by zdleaf** [comment]
Check your config - the example config uses 'q' under scene which will overwrite the macro key

```
    scene = {
      diff_preference = 'unified', -- unified or split
      keymaps = {
        quit = 'q'
      }
    }
```
