### ISSUE TITLE
live_gutter is stopped working on v0.2.2

### ISSUE THREAD

**Issue by mrded** [tanvirtin/vgit.nvim#365]
### Description

I noticed that JS/TS projects stopped showing `live_gutter` after updating to v0.2.2.
Rolling back to ` v0.2.1` solves the problem. `:VGit toggle_live_gutter` makes no difference.

- nvim --version output: 
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

- Operating system: macOS 14.5 (23F79)

**Comment by mrded** [comment]
I also noticed that a version from `main` doesn't have that problem, perhaps fixed already.

**Comment by tanvirtin** [comment]
I've created a new release v0.2.3 with the latest changes from `main`, hopefully that solves this issue.
