### ISSUE TITLE
Doesn't track updates from external program

### ISSUE THREAD

**Issue by timsofteng** [tanvirtin/vgit.nvim#61]
### Description

Hello. I'm using `lazygit` to work with git. When I got to lazygit in external terminal window and make some changes (commit, revert, or whatever) and then back to nvim with enabled `vgit` it doesn't react to any changes.

Can you fix it please?

- nvim --version 0.5;
- Nixo unstable

**Comment by tanvirtin** [comment]
Hi @timsofteng I have not used `lazygit`, can you emulate what `lazygit` does with regular git commands and report the commands back to me? Detailing the problem better allows me to find a solution easier. 

I have a few more follow-up questions:
- Does the problem persist when you refresh the buffer?
- Are you still working within the directory where .git folder is located after making these changes?

**Comment by Paveloom** [comment]
Lazygit mostly just calls `git` under the hood.

Here's an example of a plain `git commit` change not being tracked by `vgit` until a buffer is reloaded:

https://user-images.githubusercontent.com/49961859/199032674-61d9ca41-1c09-47e7-b12c-a4fe10bc15aa.mp4

I think in [`gitsigns`](https://github.com/lewis6991/gitsigns.nvim) they refresh this automatically somehow.
