### ISSUE TITLE
VGit ignore colorscheme colors

### ISSUE THREAD

**Issue by timsofteng** [tanvirtin/vgit.nvim#62]
Hello. i've noticed vgit ignore colorsheme in column which include signs.
Look at  the screenshot please:

![image](https://user-images.githubusercontent.com/51912173/124766508-a8a12980-df3f-11eb-996e-584d2e37bbbe.png)

**Comment by tanvirtin** [comment]
Hi @timsofteng this is an issue related to your colorscheme. Judging from the screenshot I am guessing you are using [gruvbox](https://github.com/morhetz/gruvbox) colorscheme. When you inspect these [lines](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L545-L548) you can see that the LineNr highlight is not the same as SignColumn, which is the reason you are seeing that.

This should not be a problem in most colorschemes as they handle this scenario. This project is not responsible for fixing issues related to external colorscheme issues.

If you want to fix it you can add `highlight! link SignColumn LineNr`  as autocmd in your dotfile configurations.

Closing this issue.

**Comment by timsofteng** [comment]
> Hi @timsofteng this is an issue related to your colorscheme. Judging from the screenshot I am guessing you are using [gruvbox](https://github.com/morhetz/gruvbox) colorscheme. When you inspect these [lines](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L545-L548) you can see that the LineNr highlight is not the same as SignColumn, which is the reason you are seeing that.
> 
> This should not be a problem in most colorschemes as they handle this scenario. This project is not responsible for fixing issues related to external colorscheme issues.
> 
> If you want to fix it you can add `highlight! link SignColumn LineNr` as autocmd in your dotfile configurations.
> 
> Closing this issue.

I've tried three different colorschemes and all thee display sings in wrong way.
In other hand `gitsigns` works correctly

It is gitsigns:
![image](https://user-images.githubusercontent.com/51912173/124891026-44cf3d00-dfe1-11eb-9066-4fc3e0da27be.png)

It is vgit:
![image](https://user-images.githubusercontent.com/51912173/124891066-4dc00e80-dfe1-11eb-8063-1839dbce3cfa.png)

Are you sure the problem is with colorscheme?

**Comment by tanvirtin** [comment]
Yes I am sure.

The reason none of those colorscheme work is again because of [this](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L545-L548).

The reason gitsigns works is because they implemented highlights of some other plugin such as [vim-signify](https://github.com/mhinz/vim-signify) on top of their own highlights.

Your gruvbox colorscheme fixes the SignColumn and LineNr issue by implementing highlights which belongs to [vim-signify](https://github.com/mhinz/vim-signify) as you can see from [here](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L766-L768).

If you don't like my previous solution you can also try this in your setup:

```lua
require('vgit').setup({
    hunk_sign = {
        priority = 10,
        signs = {
            add = {
                name = 'SignifySignAdd',
                hl = 'SignifySignAdd',
                text = '│'
            },
            remove = {
                name = 'SignifySignChange',
                hl = 'SignifySignChange',
                text = '│'
            },
            change = {
                name = 'SignifySignDelete',
                hl = 'SignifySignDelete',
                text = '│'
            },
        },
    },
})
```
Hope this helps!
