### ISSUE TITLE
VGit doesn't work on first opened buffer

### ISSUE THREAD

**Issue by logdot** [tanvirtin/vgit.nvim#63]
### Description

Most of the plugin doesn't work on the first opened buffer, only on subsequent ones. Doing `:e file` to reload the file fixes the issue. The plugin works on new buffers created using splits or tabs. Only a couple of functions like `VGit diff` and `VGit hunks_quickfix_list` still work all of the time.

- nvim --version output: 
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
- Operating system: 
Ubuntu LTS running on windows wsl2

WSL operating system:
`Ubuntu 20.04.2 LTS (Focal Fossa)`

WSL version:
`5.10.16.3-microsoft-standard-WSL2`

Windows version:
`Windows 11 Version 21H2 (OS Build 22000.51)`

**Comment by tanvirtin** [comment]
Hi @logdot. Thanks for taking the time to post this issue and help VGit be a better plugin. I was able to reproduce it locally and issue a fix. Let me know if it resolves your problem.

**Comment by logdot** [comment]
@tanvirtin It works perfectly now. Thanks for going through the trouble of fixing my issue
