### ISSUE TITLE
:VGit hunk_stage

### ISSUE THREAD

**Issue by fedoranvar** [tanvirtin/vgit.nvim#66]
**Describe the solution you'd like**

Thank you for time and effort for this plugin.
Currently, i've switched from gitsigns over to it

But i miss ability to stage hunks from within buffer
... or i overlooked it?

Thank you!

**Comment by tanvirtin** [comment]
@fedoranvar Thanks for bringing this up. Appreciate your feedback, I have been meaning to add this feature for a while, but been getting busy with IRL work. I should hopefully add this one in the near future for sure!

**Comment by fedoranvar** [comment]
Thank you!
