### ISSUE TITLE
A bug related to scheduling?

### ISSUE THREAD

**Issue by the-noob-coder69** [tanvirtin/vgit.nvim#70]
### Description

I don't know why but continuously i am getting `Error executing vim.schedule lua callback: ...acker/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: /home/shantnu/.config/nvim/lua/config/vgit-nvim.lua:91: attempt to call global 'round' (a nil value)` for some reason. What is this and how do I stop it? This error is irritating ast i have to press enter whenever it pops up

- nvim --version output: 
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-d07uyf/neovim-0.5.0+ubuntu2+git202107201521-2475161de-d569569c9=. -fstack-protector-str
ong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unus
ed-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common
 -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build
/neovim-d07uyf/neovim-0.5.0+ubuntu2+git202107201521-2475161de-d569569c9/build/config -I/build/neovim-d07uyf/neovim-0.5.0+ubuntu2+git202107201521-2475161
de-d569569c9/src -I/build/neovim-d07uyf/neovim-0.5.0+ubuntu2+git202107201521-2475161de-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-d07uyf
/neovim-0.5.0+ubuntu2+git202107201521-2475161de-d569569c9/build/src/nvim/auto -I/build/neovim-d07uyf/neovim-0.5.0+ubuntu2+git202107201521-2475161de-d569
569c9/build/include
Compiled by buildd@bos02-arm64-021

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: Ubuntu arm64

**Comment by tanvirtin** [comment]
Hi,

I am guessing you copied the setup configurations from the readme. The error comes from a function round being not defined within the blame formatter. I have updated the readme, with correct setup configurations. You can copy paste it again to resolve your issues.

**Comment by the-noob-coder69** [comment]
ok lol i will try it.

**Comment by the-noob-coder69** [comment]
Thanks it worked but I don't know why there's no colour for deletion/addition/modification of lines and i tried both with just require('vgit').setup() and the one with a lot of config i will try for some more time then i might open new issue. Thought i should tell you
