### ISSUE TITLE
Signs not showing on edit/write when PWD is not the git root.

### ISSUE THREAD

**Issue by codeindulgence** [tanvirtin/vgit.nvim#72]
### Description
If the nvim PWD is a subdirectory of the git repo, diff signs do now show when a file is opened or saved.
They do show when an open buffer is changed, but disappear when the buffer is saved.

To reproduce using this repo as an example:
```
# This works as expected
cd path/to/vgit.nvim
nvim lua/vgit/init.lua
# Modify file - signs appear
:w
# Signs persist
```
```
# Reproduce error
cd path/to/vgit.nvim/lua
nvim vgit/init.lua
# Modify file - signs appear
:w
# Signs disappear
```
Setting `debug = true` then running `:VGit show_debug_logs` shows the error:
```
VGit[11:43:48]: VGit[11:43:45][init.lua/_blame_line]: fatal: no such path 'lua/lua/vgit/init.lua' in HEAD
```

- nvim --version output: 
  - NVIM v0.6.0-dev+14-gdf33f30e8
  - NVIM v0.5.0

- Operating system: 
  - Macos
  - Centos 8

Love your works and thanks!

**Comment by codeindulgence** [comment]
Nice work, thanks!

**Comment by DavidePatria** [comment]
I have a problem which might be related: when working on files in a submodule and the pwd is the top level repo which contains said submodule signs do not show
