### ISSUE TITLE
Allow all of VGit functionality to be used outside of a git repository

### ISSUE THREAD

**Issue by tanvirtin** [tanvirtin/vgit.nvim#79]
As a user VGit should be usable when current working directory is not a git directory. Currently this feature exists on text editors like VScode which can be really helpful sometimes.

**Comment by bew** [comment]
How does that work then, what kind of functionality you want to work?
AFAIK all features of vgit comes from git being available

**Comment by tanvirtin** [comment]
@bew you can execute git commands from anywhere in the system by pointing it to the directory/subdirectory where a .git exists. In order to achieve this you need to use the `-C` flag followed by the directory. For example:

```
git -C path/to/your/repo ls-files
```

Goal is to make any buffer no matter where you open it from within the filesystem to work seamlessly as if you were in the .git directory.

Achieving this will be a bit tricky because of the tight coupling, but achievable none the less.
