### ISSUE TITLE
How can I open the git history preview window like example picture?

### ISSUE THREAD

**Issue by ChiTungFok** [tanvirtin/vgit.nvim#82]
I use the default config and use **:VGit buffer_history** command but does not meet my expectations. It's performance like this: 
<img width="1920" alt="截屏2021-08-16 上午1 03 27" src="https://user-images.githubusercontent.com/34561664/129486466-7603b394-0dde-44e8-95ef-366675a9b036.png">

So How can I open the git history preview window like example picture? I like this plugin and thank you very much for your work.

**Comment by tanvirtin** [comment]
Hey @ChiTungFok, I believe the window layout is set to be `horizontal` by default. However, to get the view you see in the README.md you need to set that to `vertical`, you can change this by doing the following when instantiating the plugin:
```
require('vgit').setup({
    diff_preference = 'vertical',
})
```
You can also change it on the fly using the following command:

```
:VGit set_diff_preference vertical
```

Glad to hear you are enjoying the plugin! Hopefully this solves your issue! Let me know if you encounter any further issues, thanks.
