### ISSUE TITLE
Getting the error on startup 

### ISSUE THREAD

**Issue by collegeimprovements** [tanvirtin/vgit.nvim#90]
I'm getting the following error on startup after updating the vgit.nvim. 

<img width="1378" alt="Screenshot 2021-08-20 at 8 50 05 AM" src="https://user-images.githubusercontent.com/1519705/130173992-835b5382-11f2-4953-855d-08f7b3476c03.png">

Please let me know if more information is required.

**Comment by tanvirtin** [comment]
My bad, working on a recent features ended up in creating a bug. Should be fixed now! Sorry for the inconvenience.

**Comment by collegeimprovements** [comment]
Thanks a lot :)
