### ISSUE TITLE
Highlight Groups Unset

### ISSUE THREAD

**Issue by Chaitanyabsprip** [tanvirtin/vgit.nvim#99]
### Description

Highlight Groups are not being set automatically.

- nvim --version output: 0.5
- Operating system:  MacOS BigSur 11.5.2

**Comment by tanvirtin** [comment]
Hi there, thanks for the issue. Can you give me a bit more information on how to replicate this? I am failing to reproduce this on my end. What plugins and colorschemes are you using for your configuration?

**Comment by fedoranvar** [comment]
I had this king of issue.

It was caused by applying my colorscheme in 'config'-section of packer's use.I've moved section out from it - and now all is working
![image](https://user-images.githubusercontent.com/52028706/132287861-23301c09-2908-4699-b73f-e879fc5b86be.png)

**Comment by tanvirtin** [comment]
If this is still an issue feel free to reopen this issue.
